=== alecnunn/bookresources/GameDevelopment/Game Programming Gems 4/01 General Programming/13 Price/sample/generated/powerups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was generated by the XDS toolkit utility 'xdsMakeSchema'
     For more information about the XDS toolkit see the XDS Resources
     web page at "http://www.suddenpresence.com/xds" -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:complexType name="PowerUp_t" final="#all">
		<xs:sequence>
			<xs:element name="szName">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="szImage">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="iHealth" type="xs:byte"/>
			<xs:element name="iInvulnerability" type="xs:unsignedByte"/>
			<xs:element name="iFastMove" type="xs:unsignedByte"/>
			<xs:element name="iHighJump" type="xs:unsignedByte"/>
			<xs:element name="iStunPlayer" type="xs:unsignedByte"/>
			<xs:element name="iLifeUp" type="xs:unsignedByte"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="_xdsType1" final="#all">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="entry" type="PowerUp_t"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Powerups">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Powerup">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="_xdsGlobalElements"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="_xdsGlobalElements">
		<xs:choice>
			<xs:element name="g_PowerUps" type="_xdsType1"/>
		</xs:choice>
	</xs:group>
</xs:schema>

=== alecnunn/bookresources/GameDevelopment/Game Programming Gems 4/01 General Programming/13 Price/sample/powerups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Global comment  -->
<Powerups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="powerups.xsd">
	<!-- Document comment  -->
	<Powerup>
		<!-- Record comment  -->
		<g_PowerUps>
			<!-- Element comment  -->
			<entry>
				<szName>Turbo Jet</szName>
				<szImage>jets.png</szImage>
				<iHealth>0</iHealth>
				<iInvulnerability>0</iInvulnerability>
				<iFastMove>30</iFastMove>
				<iHighJump>0</iHighJump>
				<iStunPlayer>0</iStunPlayer>
				<iLifeUp>0</iLifeUp>
			</entry>
			<entry>
				<szName>Jump Boot</szName>
				<szImage>boots.png</szImage>
				<iHealth>0</iHealth>
				<iInvulnerability>0</iInvulnerability>
				<iFastMove>0</iFastMove>
				<iHighJump>120</iHighJump>
				<iStunPlayer>0</iStunPlayer>
				<iLifeUp>0</iLifeUp>
			</entry>
			<entry>
				<szName>Shields</szName>
				<szImage>shield.png</szImage>
				<iHealth>0</iHealth>
				<iInvulnerability>20</iInvulnerability>
				<iFastMove>0</iFastMove>
				<iHighJump>0</iHighJump>
				<iStunPlayer>0</iStunPlayer>
				<iLifeUp>0</iLifeUp>
			</entry>
			<entry>
				<szName>Life Up</szName>
				<szImage>heart.png</szImage>
				<iHealth>0</iHealth>
				<iInvulnerability>0</iInvulnerability>
				<iFastMove>0</iFastMove>
				<iHighJump>0</iHighJump>
				<iStunPlayer>0</iStunPlayer>
				<iLifeUp>1</iLifeUp>
			</entry>
			<entry>
				<szName>Poison</szName>
				<szImage>vial.png</szImage>
				<iHealth>-20</iHealth>
				<iInvulnerability>0</iInvulnerability>
				<iFastMove>0</iFastMove>
				<iHighJump>0</iHighJump>
				<iStunPlayer>3</iStunPlayer>
				<iLifeUp>0</iLifeUp>
			</entry>
			<entry>
				<szName>Med Kit</szName>
				<szImage>medkit.png</szImage>
				<iHealth>25</iHealth>
				<iInvulnerability>0</iInvulnerability>
				<iFastMove>0</iFastMove>
				<iHighJump>0</iHighJump>
				<iStunPlayer>0</iStunPlayer>
				<iLifeUp>0</iLifeUp>
			</entry>
		</g_PowerUps>
	</Powerup>
</Powerups>
